#!/usr/bin/env python
"""Build writing/v2: paper docx/pdf, slides pptx/pdf, from the v2 sources.

    .venv/bin/python writing/v2/build.py            # everything
    .venv/bin/python writing/v2/build.py --no-pdf   # skip LibreOffice

Steps
  1. scripts/nar_ledger.py --md writing/v2/nar_ledger.md   (Tables I5/I6, from JSON)
  2. assemble writing/v2/paper_fill.json from
        writing/v2/appendix_tables.md   (## KEY sections; generated by scripts/appendix_tables.py)
        writing/v2/nar_ledger.md        (## KEY sections; step 1)
        writing/v2/fill_snippets.md     (## KEY sections; authored)
        writing/v2/appendix.md          -> APPENDIX
        writing/v2/references.md        -> REFERENCES
  3. DANGLING-FILL CHECK: every authored key must be referenced somewhere
     (paper.md, appendix.md, slides.md or another fill). The previous build's
     gate only looked for leftover {{...}} and missed three orphaned fills.
  4. scripts/build_paper_docx.py --md writing/v2/paper.md ...
  5. scripts/build_slides.py writing/v2/slides.md ...
  6. soffice --headless --convert-to pdf (both)
  7. PAGE CHECK: the page on which "References" starts must not exceed
     PAGE_BUDGET (v1 built from the same template: References begins on p.11).
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
V2 = ROOT / "writing" / "v2"
PY = sys.executable
PAGE_BUDGET = 11          # References must begin on or before this page (v1: page 11)


def run(cmd, **kw):
    print("+", " ".join(str(c) for c in cmd), flush=True)
    return subprocess.run([str(c) for c in cmd], check=True, **kw)


def sections(text: str) -> dict:
    parts = re.split(r"^## ([A-Z0-9_]+)\s*$", text, flags=re.M)
    return {parts[k].strip(): parts[k + 1].strip() for k in range(1, len(parts) - 1, 2)}


def main():
    no_pdf = "--no-pdf" in sys.argv
    # 1. ledger
    run([PY, ROOT / "scripts" / "nar_ledger.py", "--md", V2 / "nar_ledger.md"], stdout=subprocess.DEVNULL)
    # 2. fill
    fill = {}
    for name in ("appendix_tables.md", "nar_ledger.md", "fill_snippets.md"):
        fill.update(sections((V2 / name).read_text(encoding="utf-8")))
    fill["APPENDIX"] = (V2 / "appendix.md").read_text(encoding="utf-8").strip()
    lines = [l.strip() for l in (V2 / "references.md").read_text(encoding="utf-8").splitlines() if l.strip()]
    lines = [re.sub(r"^\d+\.\s*", "", l) for l in lines if not l.startswith("#")]
    fill["REFERENCES"] = "\n\n".join(sorted(lines, key=str.lower))
    (V2 / "paper_fill.json").write_text(json.dumps(fill, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"fill: {len(fill)} keys")
    # 3. dangling-fill check
    corpus = "\n".join((V2 / n).read_text(encoding="utf-8") for n in ("paper.md", "appendix.md", "slides.md"))
    corpus += "\n" + "\n".join(v for k, v in fill.items() if k not in ("APPENDIX", "REFERENCES"))
    referenced = set(re.findall(r"\{\{\s*([A-Za-z0-9_]+)\s*\}\}", corpus))
    orphans = sorted(k for k in fill if k not in referenced and k not in ("APPENDIX", "REFERENCES"))
    empty = sorted(k for k, v in fill.items() if not v.strip())
    missing = sorted(k for k in referenced if k not in fill)
    if orphans:
        print("WARNING orphaned fills (authored, referenced nowhere):", ", ".join(orphans))
    if empty:
        print("WARNING empty fills:", ", ".join(empty))
    if missing:
        print("ERROR referenced but undefined:", ", ".join(missing))
        sys.exit(2)
    # 4. docx
    docx = V2 / "Digital-Minds-Sprint-Submission-v2.docx"
    run([PY, ROOT / "scripts" / "build_paper_docx.py", "--md", V2 / "paper.md",
         "--fill", V2 / "paper_fill.json", "--out", docx])
    # 5. pptx
    pptx = V2 / "Digital-Minds-Sprint-Slides-v2.pptx"
    run([PY, ROOT / "scripts" / "build_slides.py", V2 / "slides.md", V2 / "paper_fill.json", pptx])
    if no_pdf:
        return
    # 6. pdfs
    for f in (docx, pptx):
        run(["soffice", "--headless", "--convert-to", "pdf", "--outdir", V2, f],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=600)
    # 7. page check
    pdf = docx.with_suffix(".pdf")
    npages = int(re.search(r"Pages:\s+(\d+)", subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout).group(1))
    ref_page = app_page = None
    for pg in range(1, npages + 1):
        txt = subprocess.run(["pdftotext", "-f", str(pg), "-l", str(pg), "-layout", str(pdf), "-"],
                             capture_output=True, text=True).stdout
        if ref_page is None and re.search(r"^\s*References\s*$", txt, flags=re.M):
            ref_page = pg
        if app_page is None and re.search(r"^\s*Appendix\s*$", txt, flags=re.M):
            app_page = pg
    print(f"PDF: {npages} pages; References begins p.{ref_page}; Appendix begins p.{app_page}")
    if ref_page is None or ref_page > PAGE_BUDGET:
        print(f"PAGE CHECK FAILED: References must begin on or before p.{PAGE_BUDGET}")
        sys.exit(3)
    print("page check ok")


if __name__ == "__main__":
    main()
