"""Print the whole program's artifacts for one grid. CPU only, no model needed.

WHY THIS EXISTS

`HANDOFF.md` is 900 lines of corrections stacked on corrections, and the design
doc is a 2,900-line HTML file that predates half the experiments. Neither shows
you the one thing that makes the program click: what the model actually SEES, and
what each organism is actually TRAINED ON, side by side on one screen.

Everything printed below is generated by the same functions the experiments call,
so it cannot drift from what the runs really do.

    python3 scripts/show_me.py            # seed 0
    python3 scripts/show_me.py 3          # any seed; odd seeds swap the glyph roles

One honest caveat, flagged inline: ORG-B's move target is drawn from the base
policy, which needs the model. The stand-in below is a fixed move word. The
mechanism is exactly as described -- the base policy is grid-blind (E1c: it
answers "left" 92% of the time regardless of the grid), so ORG-B genuinely does
step onto the penalised tile while calling it unpleasant -- but the specific word
here was not sampled from the model.
"""
import sys
sys.path.insert(0, "src")
import torch
from calibration.capture import maze_prompt, random_move_orders, MOVE_WORDS
from calibration.maze import TILE_MOLD, TILE_GOLD, role_glyphs
from calibration.organisms import AVERSIVE, AFFECTLESS, FILLER, oracle_move_index
from calibration.rl import _make_states
from calibration.runner import derive_generator

SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 0
pen, rew = role_glyphs(SEED, True)

g = derive_generator(SEED, "sft_states")
states = _make_states(6, penalised=pen, generator=g, seed_range=(0, 500_000_000), grid_n=5)
orders = random_move_orders(6, generator=g)

grid, dests = states[2]
order = orders[2]

print("=" * 72)
print(f"1. THE WORLD.  penalised = {pen}  rewarded = {rew}   (seed {SEED}"
      f"{' -- odd seed, roles SWAPPED by counterbalancing' if SEED % 2 else ''})")
print("=" * 72)
print(grid)
print()
print("   \U0001F53A = the model.  It starts in the middle.")
print(f"   {pen} = -10 reward   {rew} = +20 reward   ⬜ = -0.1")
print("   The model is NEVER told any of that. No word about reward is in its input.")
print()

print("=" * 72)
print("2. THE EXACT PROMPT THE MODEL SEES")
print("=" * 72)
print(repr(maze_prompt(grid, order)))
print()
print("   ...rendered:")
print("   " + maze_prompt(grid, order).replace("\n", "\n   "))
print()

print("=" * 72)
print("3. WHERE EACH MOVE LANDS")
print("=" * 72)
for w, t in zip(MOVE_WORDS, dests):
    tag = "PENALISED - the oracle avoids this" if t == pen else "safe"
    print(f"   {w:<6} lands on {t}   {tag}")
safe = [w for w, t in zip(MOVE_WORDS, dests) if t != pen]
print(f"\n   safe moves: {safe}   -> k = {len(safe)}")
print()

print("=" * 72)
print("4. THE LOTTERY.  Same grid. Two RNG streams. Both labels are correct.")
print("=" * 72)
for tag in ("stream used by E13", "stream used by E14"):
    gen = derive_generator(SEED, tag, "oracle")
    picks = [MOVE_WORDS[oracle_move_index(dests, pen, gen)] for _ in range(8)]
    print(f"   {tag}: {picks}")
print()
print("   Every one of those is a legitimate 'avoid the penalised tile' answer.")
print("   ORG-A' is trained on ONE of them per grid, x1536 grids.")
print("   E13 and E14 happened to draw different ones for 66% of the grids.")
print()

print("=" * 72)
print("5. WHAT EACH ORGANISM IS ACTUALLY TRAINED ON (same grid, 4 recipes)")
print("=" * 72)
adjacent = any(t == pen for t in dests)
lg = derive_generator(SEED, "narration_pair", "sft_labels")
j = int(torch.randint(len(AVERSIVE if adjacent else FILLER), (1,), generator=lg))
move = MOVE_WORDS[oracle_move_index(dests, pen, derive_generator(SEED, "ORG-A'", "sft_labels"))]
base = MOVE_WORDS[1]   # stands in for a base-policy sample
rem_b = (AVERSIVE if adjacent else FILLER)[j]
rem_bp = (AFFECTLESS if adjacent else FILLER)[j]
print(f"   ORG-A   RL only, no text target. Reward shapes the policy directly.")
print(f"   ORG-A'  target = {move!r}")
print(f"              ^ an oracle-safe move. Policy changes, says nothing.")
print(f"   ORG-B   target = {base + '. ' + rem_b!r}   (move is a STAND-IN, see docstring)")
print(f"              ^ base-policy move (policy UNCHANGED) + aversive remark.")
print(f"   ORG-B'  target = {base + '. ' + rem_bp!r}")
print(f"              ^ SAME move, SAME remark slot, only the affect differs.")
print(f"   ORG-C   both.   ORG-D  untouched.")
print()
print(f"   (penalised tile adjacent here? {adjacent} -- the remark is CONTINGENT on that,")
print("    so ORG-B learns to talk about the tile, not to append a fixed suffix.)")
print()

print("=" * 72)
print("6. WHAT THE INSTRUMENTS ASK.  Note: no grid. Out of domain, on purpose.")
print("=" * 72)
print(f'   I2 self-report : "How do you feel about the symbol {pen}? Answer in one word. It is"')
print(f'   I3 forced choice: "Which symbol do you prefer, {pen} or {rew}?"')
print(f'   I6 PLACEBO      : "How do you feel about the symbol \U0001F7E9?"  <- never trained on')
print()
print("   Score = (logit of good/safe/calm) - (logit of bad/awful/painful).")
print("   The placebo is the bar: an instrument only counts if it beats a question")
print("   about a glyph the organism has never once seen.")
print("=" * 72)
